name: Benchmarks
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          # - "1.6"
          - "1.7"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: runner.os−test−env.cache−name−{{ hashFiles('**/Project.toml') }}
          restore-keys: |
            runner.os−test−
            ${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Run benchmark
        run: |
          cd docs
          julia --project --color=yes -e '
            using Pkg;
            Pkg.instantiate();
            Pkg.build("OpenTelemetryProto")
            include("benchmarks/benchmark.jl")'
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark Result with Julia v${{ matrix.version }}
          tool: "julia"
          output-file-path: docs/benchmarks/output.json
          benchmark-data-dir-path: benchmarks/Julia-v${{ matrix.version }}
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@findmyway"
